- hosts: bastion
  sudo: yes
  user: Ryo
  roles:
    - packages
    - { tags: golang,   role: golang, go_version: 1.4.2 }
    - { tags: h2o,      role: h2o,    h2o_version: 1.3.1}
    - { tags: react,    role: react }
    - { tags: ruby,    role: ruby }
    - { tags: dotfiles, role: dotfiles }
