- hosts: bastion
  sudo: yes
  user: Ryo
  roles:
    - { tags: packages, role: packages }
    - { tags: golang,   role: golang, go_version: 1.5beta2 }
    - { tags: h2o,      role: h2o,    h2o_version: 1.3.1}
    - { tags: js,    role: js }
    - { tags: ruby,    role: ruby }
    - { tags: dotfiles, role: dotfiles }
