- hosts: bastion
  sudo: yes
  roles:
    - { tags: packages,     role: packages }
    - { tags: golang,       role: golang, go_version: 1.5 }
    - { tags: h2o,          role: h2o,    h2o_version: 1.4.2}
    - { tags: js,    role: js }
    - { tags: ruby,    role: ruby }
    - { tags: python,    role: python }
    - { tags: dotfiles, role: dotfiles }
