- apt: update_cache=yes

- apt: name={{ item }} state=present
  with_items:
    - emacs
    - zsh
    - make
    - mysql-client-5.6

- pip: name={{ item }} state=present executable=pip2
  with_items:
    - awscli
    - mycli
    - httplib2
