- apt: update_cache=yes

- apt: name={{ item }} state=present
  with_items:
    - sensu
    - ruby2.0

- file: src=/usr/bin/ruby2.0 path=/usr/bin/ruby state=link

- file: src=/usr/bin/gem2.0 path=/usr/bin/gem state=link

- gem: executable=gem2.0 name=sensu-plugin
