- user: name={{ ansible_ssh_user }} shell=/usr/bin/zsh

- copy: src={{ item }} dest=~{{ ansible_ssh_user }}/.{{ item }} owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }}
  with_items:
    - zshrc
    - zsh.d/
    - emacs.d/
    - screenrc
    - gitconfig
    - snippets

- file: path=~{{ ansible_ssh_user }}/.bak.emacs owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} state=directory

- apt: name={{ item }}
  with_items:
    - lv
    - xsel

- file: path=/usr/share/doc/git/contrib/diff-highlight/diff-highlight mode=0755

- shell: GOPATH=~{{ ansible_ssh_user }}/.golang /usr/local/go/bin/go get -u {{ item }}
  with_items:
    - github.com/tools/godep
    - github.com/peco/peco/cmd/peco
