- user: name=ubuntu shell=/usr/bin/zsh

- copy: src={{ item }} dest=~/.{{ item }}
  with_items:
    - zshrc
    - zsh.d/
    - emacs.d/
    - screenrc
    - gitconfig
    - snippets
    - eslintrc
  sudo: no

- file: path=~/.bak.emacs state=directory
  sudo: no

- apt: name={{ item }}
  with_items:
    - lv
    - xsel
    - texinfo

- file: path=/usr/share/doc/git/contrib/diff-highlight/diff-highlight mode=0755

- shell: GOPATH=~/.golang /usr/local/go/bin/go get -u {{ item }}
  with_items:
    #- github.com/tools/godep
    - github.com/peco/peco/cmd/peco
  sudo: no

- copy: src=~/.ssh/id_rsa dest=~/.ssh/id_rsa mode=0600
  sudo: no
