- user: name={{ ansible_ssh_user }} shell=/usr/bin/zsh

- copy: src={{ item }} dest=~{{ ansible_ssh_user }}/.{{ item }} owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }}
  with_items:
    - zshrc
    - zsh.d/
    - emacs.d/

- file: path=~{{ ansible_ssh_user }}/.bak.emacs owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} state=directory