- apt: name={{ item }}
  with_items:
    - nodejs
    - npm

- shell: update-alternatives --install /usr/bin/node node /usr/bin/nodejs 10

- npm: name={{ item }} global=yes
  with_items:
    - npm
    - jsxhint
    - gulp
    - webpack
    - eslint
    - babel-eslint
    - eslint-plugin-react
